export {
  AMBIGUOUS_LEGACY_SERVICE_KEYS,
  CANONICAL_SERVICE_KEYS,
  CANONICAL_SERVICE_KEY_SET,
  CANONICAL_SERVICE_REGISTRY,
  CLAIM_PREP_SERVICE_GROUPS,
  LEGACY_PROVIDER_TYPE_LAYOUTS,
  LEGACY_SERVICE_ALIASES,
  PROFILE_TYPES,
  SERVICE_GROUP_LAYOUTS,
  SERVICE_GROUPS,
  classifyServiceNeedLevel,
  getCanonicalServiceDefinition,
  getCanonicalServiceGroupIds,
  getServiceGroupLayout,
  isServiceMatchingEligible,
  isServicePubliclyEligible,
  normalizeServiceKey,
} from "../../shared/canonicalServiceRegistry.js";
