export const SERVICE_GROUPS = {
  optical_retail: {
    label: "Optica si produse",
    helper: "Produse si servicii comerciale disponibile in locatie.",
    ids: {
      eyeglasses: "Ochelari de vedere",
      frames: "Rame",
      prescription_lenses: "Lentile pe reteta",
      sunglasses: "Ochelari de soare",
      prescription_sunglasses: "Ochelari de soare cu dioptrii",
      children_frames: "Rame pentru copii",
      sports_glasses: "Ochelari sport",
      safety_glasses: "Ochelari de protectie",
      accessories: "Accesorii ochelari",
    },
  },
  lenses_and_measurements: {
    label: "Lentile si masuratori",
    helper: "Optiuni pentru lentile, masuratori si personalizare tehnica.",
    ids: {
      single_vision_lenses: "Lentile monofocale",
      progressive_lenses: "Lentile progresive",
      office_lenses: "Lentile office / intermediare",
      reading_lenses: "Lentile pentru aproape",
      thin_lenses: "Lentile subtiate",
      photochromic_lenses: "Lentile heliomate",
      polarized_lenses: "Lentile polarizate",
      blue_light_lenses: "Protectie lumina albastra",
      prism_lenses: "Lentile prismatice",
      pd_measurement: "Masurare distanta pupilara",
      digital_centering: "Centrare digitala lentile",
    },
  },
  optometry: {
    label: "Optometrie",
    helper: "Servicii de evaluare optometrica si recomandari pentru corectie vizuala.",
    ids: {
      optometry_consultation: "Consult optometric",
      visual_acuity_test: "Test acuitate vizuala",
      refraction: "Determinare dioptrii",
      autorefractometry: "Autorefractometrie",
      binocular_vision: "Evaluare vedere binoculara",
      dry_eye_screening: "Screening ochi uscat",
      color_vision_test: "Test vedere cromatica",
      occupational_vision: "Evaluare vedere pentru activitate profesionala",
    },
  },
  contact_lenses: {
    label: "Lentile de contact",
    helper: "Adaptare, proba si monitorizare pentru lentile de contact.",
    ids: {
      contact_lenses: "Lentile de contact",
      contact_lens_consultation: "Consult lentile de contact",
      contact_lens_fitting: "Adaptare lentile de contact",
      contact_lens_trial: "Proba lentile de contact",
      toric_contact_lenses: "Lentile torice",
      multifocal_contact_lenses: "Lentile multifocale",
      rgp_lenses: "Lentile rigide gaz-permeabile",
      scleral_lenses: "Lentile sclerale",
      contact_lens_followup: "Control lentile de contact",
    },
  },
  ophthalmology_consults: {
    label: "Consultatii oftalmologice",
    helper: "Consultatii medicale si controale efectuate de medic oftalmolog.",
    ids: {
      ophthalmology_consultation: "Consult oftalmologic",
      complete_eye_exam: "Examinare oftalmologica completa",
      prescription_check: "Verificare reteta ochelari",
      eye_pressure_check: "Masurare tensiune intraoculara",
      fundus_exam: "Examinare fund de ochi",
      anterior_segment_exam: "Examinare segment anterior",
      followup_consultation: "Control oftalmologic",
      second_opinion: "A doua opinie medicala",
    },
  },
  investigations: {
    label: "Investigatii si aparatura",
    helper: "Investigatii disponibile in locatie, in functie de dotari si personal autorizat.",
    ids: {
      oct: "OCT",
      visual_field_analyzer: "Camp vizual",
      fundus_camera: "Fotografie fund de ochi",
      pachymeter: "Pahimetrie",
      biometer: "Biometrie",
      corneal_topography: "Topografie corneana",
      keratometry: "Keratometre / keratometrie",
      tonometry: "Tonometrie",
      gonioscopy: "Gonioscopie",
      ultrasound: "Ecografie oculara",
      specular_microscopy: "Microscopie speculara",
      angiography: "Angiografie retiniana",
    },
  },
  specialties: {
    label: "Arii medicale specializate",
    helper: "Zone de expertiza medicala sau supraspecializare declarate de locatie.",
    ids: {
      retina_consultation: "Retina",
      glaucoma_consultation: "Glaucom",
      cataract_consultation: "Cataracta",
      cornea_consultation: "Cornee",
      pediatric_ophthalmology: "Oftalmologie pediatrica",
      strabismus: "Strabism",
      neuro_ophthalmology: "Neuro-oftalmologie",
      uveitis: "Uveita",
      myopia_management: "Managementul miopiei",
      dry_eye_management: "Management ochi uscat",
      diabetic_retinopathy: "Retinopatie diabetica",
      macular_degeneration: "Degenerescenta maculara",
      emergency_ophthalmology: "Urgente oftalmologice",
    },
  },
  procedures_surgery: {
    label: "Proceduri si chirurgie",
    helper: "Proceduri medicale care necesita control si validare atenta inainte de publicare.",
    ids: {
      cataract_surgery: "Chirurgie cataracta",
      refractive_surgery: "Chirurgie refractiva",
      laser_procedures: "Proceduri laser",
      yag_laser: "Laser YAG",
      retinal_laser: "Laser retinian",
      intravitreal_injections: "Injectii intravitreene",
      eyelid_surgery: "Chirurgie pleoape",
      chalazion_treatment: "Tratament salazion",
      minor_eye_procedures: "Proceduri oftalmologice minore",
    },
  },
  children_and_prevention: {
    label: "Copii si preventie",
    helper: "Servicii pentru copii, screening si monitorizare preventiva.",
    ids: {
      children_eye_exam: "Consult copii",
      pediatric_refraction: "Determinare dioptrii copii",
      amblyopia_screening: "Screening ambliopie",
      strabismus_screening: "Screening strabism",
      school_screening: "Screening scolar",
      myopia_control_children: "Control miopie copii",
      vision_therapy: "Terapie vizuala",
    },
  },
  technical_activities: {
    label: "Atelier si activitati tehnice",
    helper: "Servicii tehnice pentru ochelari si lentile, realizate in magazin sau atelier.",
    ids: {
      eyeglasses_adjustment: "Reglaj ochelari",
      eyeglasses_repair: "Reparatii ochelari",
      lens_fitting: "Montaj lentile",
      frame_repair: "Reparatii rame",
      screw_replacement: "Inlocuire suruburi / pernute",
      lens_replacement: "Inlocuire lentile in rama existenta",
      frame_cleaning: "Curatare ochelari",
      workshop_orders: "Comenzi atelier optic",
    },
  },
  b2b_services: {
    label: "B2B si laborator",
    helper: "Servicii pentru laboratoare, furnizori sau colaborari profesionale.",
    ids: {
      optical_laboratory: "Laborator optic",
      lens_edging_b2b: "Montaj lentile B2B",
      wholesale_frames: "Distributie rame",
      wholesale_lenses: "Distributie lentile",
      equipment_supplier: "Echipamente optica / oftalmologie",
      service_equipment: "Service echipamente",
      professional_training: "Training profesional",
    },
  },
};

export const CLAIM_PREP_SERVICE_GROUPS = ["optical_retail", "lenses_and_measurements", "optometry", "contact_lenses", "technical_activities"];
