export const PROVIDER_SERVICE_AREAS = [
  { key: "optical", label: "Optică și produse" },
  { key: "clinical", label: "Consultații și investigații" },
  { key: "specialties", label: "Specializări medicale" },
  { key: "procedures", label: "Proceduri și chirurgie" },
];

export const PROVIDER_SERVICE_SECTIONS = [
  {
    key: "optical_products",
    area: "optical",
    title: "Produse optice",
    publicLabel: "Ochelari și produse optice",
    description: "Rame, ochelari și produse disponibile direct în locație.",
    items: [
      { group: "optical_retail", id: "eyeglasses" },
      { group: "optical_retail", id: "frames" },
      { group: "optical_retail", id: "prescription_lenses" },
      { group: "optical_retail", id: "sunglasses" },
      { group: "optical_retail", id: "prescription_sunglasses" },
      { group: "optical_retail", id: "children_frames" },
      { group: "optical_retail", id: "sports_glasses" },
      { group: "optical_retail", id: "safety_glasses" },
      { group: "optical_retail", id: "accessories" },
    ],
  },
  {
    key: "lenses_measurements",
    area: "optical",
    title: "Lentile și măsurători",
    publicLabel: "Lentile și măsurători personalizate",
    description: "Tipuri de lentile, măsurători și centrare pentru ochelari.",
    items: [
      { group: "lenses_and_measurements", id: "single_vision_lenses" },
      { group: "lenses_and_measurements", id: "progressive_lenses" },
      { group: "lenses_and_measurements", id: "office_lenses" },
      { group: "lenses_and_measurements", id: "reading_lenses" },
      { group: "lenses_and_measurements", id: "thin_lenses" },
      { group: "lenses_and_measurements", id: "photochromic_lenses" },
      { group: "lenses_and_measurements", id: "polarized_lenses" },
      { group: "lenses_and_measurements", id: "blue_light_lenses" },
      { group: "lenses_and_measurements", id: "prism_lenses" },
      { group: "lenses_and_measurements", id: "pd_measurement" },
      { group: "lenses_and_measurements", id: "digital_centering" },
    ],
  },
  {
    key: "optometry",
    area: "optical",
    title: "Optometrie",
    publicLabel: "Control vedere și dioptrii",
    description: "Evaluări optometrice și măsurarea corecției vizuale.",
    items: [
      { group: "optometry", id: "optometry_consultation" },
      { group: "optometry", id: "visual_acuity_test" },
      { group: "optometry", id: "refraction" },
      { group: "optometry", id: "autorefractometry" },
      { group: "optometry", id: "binocular_vision" },
      { group: "optometry", id: "dry_eye_screening" },
      { group: "optometry", id: "color_vision_test" },
      { group: "optometry", id: "occupational_vision" },
    ],
  },
  {
    key: "contact_lenses",
    area: "optical",
    title: "Lentile de contact",
    publicLabel: "Lentile de contact",
    description: "Produse, adaptare, probă și monitorizare.",
    items: [
      { group: "contact_lenses", id: "contact_lenses" },
      { group: "contact_lenses", id: "contact_lens_consultation" },
      { group: "contact_lenses", id: "contact_lens_fitting" },
      { group: "contact_lenses", id: "contact_lens_trial" },
      { group: "contact_lenses", id: "contact_lens_followup" },
      { group: "contact_lenses", id: "toric_contact_lenses" },
      { group: "contact_lenses", id: "multifocal_contact_lenses" },
      { group: "contact_lenses", id: "rgp_lenses" },
      { group: "contact_lenses", id: "scleral_lenses" },
    ],
  },
  {
    key: "optical_workshop",
    area: "optical",
    title: "Atelier și reparații",
    publicLabel: "Reparații și reglaje",
    description: "Reglaje, reparații și lucrări tehnice pentru ochelari.",
    items: [
      { group: "technical_activities", id: "eyeglasses_adjustment" },
      { group: "technical_activities", id: "eyeglasses_repair" },
      { group: "technical_activities", id: "lens_fitting" },
      { group: "technical_activities", id: "frame_repair" },
      { group: "technical_activities", id: "screw_replacement" },
      { group: "technical_activities", id: "lens_replacement" },
      { group: "technical_activities", id: "frame_cleaning" },
      { group: "technical_activities", id: "workshop_orders" },
    ],
  },
  {
    key: "general_ophthalmology",
    area: "clinical",
    title: "Oftalmologie generală",
    publicLabel: "Consultații oftalmologice",
    description: "Consultații, controale și examinări efectuate de medicul oftalmolog.",
    note: "Serviciile medicale sunt publicate numai după verificarea specialistului și a condițiilor necesare.",
    items: [
      { group: "ophthalmology_consults", id: "ophthalmology_consultation" },
      { group: "ophthalmology_consults", id: "complete_eye_exam" },
      { group: "ophthalmology_consults", id: "prescription_check" },
      { group: "ophthalmology_consults", id: "eye_pressure_check" },
      { group: "ophthalmology_consults", id: "fundus_exam" },
      { group: "ophthalmology_consults", id: "anterior_segment_exam" },
      { group: "ophthalmology_consults", id: "followup_consultation" },
      { group: "ophthalmology_consults", id: "second_opinion" },
    ],
  },
  {
    key: "investigations",
    area: "clinical",
    title: "Investigații oftalmologice",
    publicLabel: "Investigații oftalmologice",
    description: "Investigații disponibile în funcție de aparatura verificată a locației.",
    items: [
      { group: "investigations", id: "oct" },
      { group: "investigations", id: "visual_field_analyzer" },
      { group: "investigations", id: "fundus_camera" },
      { group: "investigations", id: "pachymeter" },
      { group: "investigations", id: "biometer" },
      { group: "investigations", id: "corneal_topography" },
      { group: "investigations", id: "keratometry" },
      { group: "investigations", id: "tonometry" },
      { group: "investigations", id: "gonioscopy" },
      { group: "investigations", id: "ultrasound" },
      { group: "investigations", id: "specular_microscopy" },
      { group: "investigations", id: "angiography" },
    ],
  },
  {
    key: "retina_macula",
    area: "specialties",
    title: "Retină și maculă",
    publicLabel: "Retină și maculă",
    description: "Evaluarea și monitorizarea afecțiunilor retiniene și maculare.",
    items: [
      { group: "specialties", id: "retina_consultation" },
      { group: "specialties", id: "diabetic_retinopathy" },
      { group: "specialties", id: "macular_degeneration" },
    ],
  },
  {
    key: "glaucoma",
    area: "specialties",
    title: "Glaucom",
    publicLabel: "Glaucom",
    description: "Consultație și monitorizare specializată pentru glaucom.",
    items: [{ group: "specialties", id: "glaucoma_consultation" }],
  },
  {
    key: "cataract_refractive",
    area: "specialties",
    title: "Cataractă și chirurgie refractivă",
    publicLabel: "Cataractă și chirurgie refractivă",
    description: "Evaluare specializată pentru cataractă și corecție refractivă.",
    items: [{ group: "specialties", id: "cataract_consultation" }],
  },
  {
    key: "cornea_surface",
    area: "specialties",
    title: "Cornee și suprafață oculară",
    publicLabel: "Cornee și suprafață oculară",
    description: "Cornee, ochi uscat și servicii de management al miopiei.",
    items: [
      { group: "specialties", id: "cornea_consultation" },
      { group: "specialties", id: "dry_eye_management" },
      { group: "specialties", id: "myopia_management" },
    ],
  },
  {
    key: "pediatric_strabismus",
    area: "specialties",
    title: "Oftalmologie pediatrică și strabism",
    publicLabel: "Oftalmologie pediatrică",
    description: "Consultații, screening și monitorizare pentru copii.",
    items: [
      { group: "specialties", id: "pediatric_ophthalmology" },
      { group: "specialties", id: "strabismus" },
      { group: "children_and_prevention", id: "children_eye_exam" },
      { group: "children_and_prevention", id: "pediatric_refraction" },
      { group: "children_and_prevention", id: "amblyopia_screening" },
      { group: "children_and_prevention", id: "strabismus_screening" },
      { group: "children_and_prevention", id: "school_screening" },
      { group: "children_and_prevention", id: "myopia_control_children" },
      { group: "children_and_prevention", id: "vision_therapy" },
    ],
  },
  {
    key: "neuro_inflammation",
    area: "specialties",
    title: "Neuro-oftalmologie și inflamații",
    publicLabel: "Neuro-oftalmologie și uveită",
    description: "Evaluare specializată pentru afecțiuni neuro-oftalmologice și inflamatorii.",
    items: [
      { group: "specialties", id: "neuro_ophthalmology" },
      { group: "specialties", id: "uveitis" },
    ],
  },
  {
    key: "emergency_ophthalmology",
    area: "specialties",
    title: "Urgențe oftalmologice",
    publicLabel: "Urgențe oftalmologice",
    description: "Evaluarea urgențelor oftalmologice în limitele capacității locației.",
    items: [{ group: "specialties", id: "emergency_ophthalmology" }],
  },
  {
    key: "cataract_refractive_procedures",
    area: "procedures",
    title: "Cataractă și chirurgie refractivă",
    publicLabel: "Chirurgie cataractă și refractivă",
    description: "Intervenții care necesită medic, aparatură și infrastructură verificate.",
    items: [
      { group: "procedures_surgery", id: "cataract_surgery" },
      { group: "procedures_surgery", id: "refractive_surgery" },
      { group: "procedures_surgery", id: "yag_laser" },
    ],
  },
  {
    key: "retina_procedures",
    area: "procedures",
    title: "Proceduri retiniene și laser",
    publicLabel: "Proceduri retiniene și laser",
    description: "Laser retinian, injecții și alte proceduri specializate.",
    items: [
      { group: "procedures_surgery", id: "laser_procedures" },
      { group: "procedures_surgery", id: "retinal_laser" },
      { group: "procedures_surgery", id: "intravitreal_injections" },
    ],
  },
  {
    key: "oculoplastics_minor",
    area: "procedures",
    title: "Oculoplastică și proceduri minore",
    publicLabel: "Oculoplastică și proceduri minore",
    description: "Proceduri pentru pleoape și intervenții oftalmologice minore.",
    items: [
      { group: "procedures_surgery", id: "eyelid_surgery" },
      { group: "procedures_surgery", id: "chalazion_treatment" },
      { group: "procedures_surgery", id: "minor_eye_procedures" },
    ],
  },
];

export const PROVIDER_SERVICE_SECTION_BY_KEY = Object.fromEntries(
  PROVIDER_SERVICE_SECTIONS.map((section) => [section.key, section]),
);
