export const PROVIDER_SERVICE_AREAS = [
  { key: "products", label: "Produse optice" },
  { key: "professional_services", label: "Servicii profesionale" },
  { key: "technical_services", label: "Servicii tehnice" },
  { key: "medical_services", label: "Servicii medicale" },
];

export const PROVIDER_SERVICE_SECTIONS = [
  {
    key: "optical_products",
    unitKey: "optical_store",
    area: "products",
    kind: "product",
    title: "Rame, ochelari și accesorii",
    publicLabel: "Ochelari și rame",
    description: "Produsele pe care clienții le pot găsi și cumpăra în această locație.",
    items: [
      { group: "optical_retail", id: "eyeglasses" },
      { group: "optical_retail", id: "frames" },
      { group: "optical_retail", id: "prescription_lenses" },
      { group: "optical_retail", id: "sunglasses" },
      { group: "optical_retail", id: "prescription_sunglasses" },
      { group: "optical_retail", id: "children_frames" },
      { group: "optical_retail", id: "sports_glasses" },
      { group: "optical_retail", id: "safety_glasses" },
      { group: "optical_retail", id: "accessories" },
    ],
  },
  {
    key: "ophthalmic_lenses",
    unitKey: "optical_store",
    unitKeyForLaboratory: "optical_laboratory",
    area: "products",
    kind: "product_option",
    title: "Lentile oftalmice",
    publicLabel: "Lentile pentru ochelari",
    description: "Tipurile și opțiunile de lentile pentru ochelari disponibile în ofertă.",
    items: [
      { group: "lenses_and_measurements", id: "single_vision_lenses" },
      { group: "lenses_and_measurements", id: "progressive_lenses" },
      { group: "lenses_and_measurements", id: "office_lenses" },
      { group: "lenses_and_measurements", id: "reading_lenses" },
      { group: "lenses_and_measurements", id: "thin_lenses" },
      { group: "lenses_and_measurements", id: "photochromic_lenses" },
      { group: "lenses_and_measurements", id: "polarized_lenses" },
      { group: "lenses_and_measurements", id: "blue_light_lenses" },
      { group: "lenses_and_measurements", id: "prism_lenses" },
    ],
  },
  {
    key: "optical_measurements",
    unitKey: "optometry_cabinet",
    area: "professional_services",
    kind: "measurement",
    title: "Măsurători pentru ochelari",
    publicLabel: "Măsurători și centrare",
    description: "Măsurători realizate pentru alegerea și montajul corect al lentilelor.",
    items: [
      { group: "lenses_and_measurements", id: "pd_measurement" },
      { group: "lenses_and_measurements", id: "digital_centering" },
    ],
  },
  {
    key: "optometry",
    unitKey: "optometry_cabinet",
    area: "professional_services",
    kind: "professional_service",
    title: "Evaluarea vederii și dioptriilor",
    publicLabel: "Control vedere și dioptrii",
    description: "Servicii realizate în cabinetul optometric de un specialist compatibil.",
    note: "Eligibilitatea depinde de specialistul asociat și de dotările declarate ale cabinetului.",
    items: [
      { group: "optometry", id: "optometry_consultation" },
      { group: "optometry", id: "visual_acuity_test" },
      { group: "optometry", id: "refraction" },
      { group: "optometry", id: "autorefractometry" },
      { group: "optometry", id: "binocular_vision" },
      { group: "optometry", id: "dry_eye_screening" },
      { group: "optometry", id: "color_vision_test" },
      { group: "optometry", id: "occupational_vision" },
    ],
  },
  {
    key: "contact_lens_products",
    unitKey: "contact_lens_center",
    area: "products",
    kind: "product",
    title: "Produse pentru lentile de contact",
    publicLabel: "Lentile de contact",
    description: "Tipurile de lentile de contact disponibile pentru cumpărare în locație.",
    items: [
      { group: "contact_lenses", id: "contact_lenses" },
      { group: "contact_lenses", id: "toric_contact_lenses" },
      { group: "contact_lenses", id: "multifocal_contact_lenses" },
      { group: "contact_lenses", id: "rgp_lenses" },
      { group: "contact_lenses", id: "scleral_lenses" },
    ],
  },
  {
    key: "contact_lens_services",
    unitKey: "contact_lens_center",
    area: "professional_services",
    kind: "professional_service",
    title: "Adaptare și monitorizare",
    publicLabel: "Adaptare lentile de contact",
    description: "Consultație, probă, adaptare și control ulterior realizate de un specialist compatibil.",
    note: "Vânzarea lentilelor de contact nu activează automat serviciile profesionale de adaptare.",
    items: [
      { group: "contact_lenses", id: "contact_lens_consultation" },
      { group: "contact_lenses", id: "contact_lens_fitting" },
      { group: "contact_lenses", id: "contact_lens_trial" },
      { group: "contact_lenses", id: "contact_lens_followup" },
    ],
  },
  {
    key: "workshop_adjustments",
    unitKey: "optical_workshop",
    unitKeyForLaboratory: "optical_laboratory",
    area: "technical_services",
    kind: "technical_service",
    title: "Reglaje, ajustări și întreținere",
    publicLabel: "Reglaje și ajustări ochelari",
    description: "Operațiuni uzuale pentru potrivirea, întreținerea și confortul ochelarilor.",
    items: [
      { group: "technical_activities", id: "eyeglasses_adjustment" },
      { group: "technical_activities", id: "screw_replacement" },
      { group: "technical_activities", id: "frame_cleaning" },
    ],
  },
  {
    key: "workshop_repairs",
    unitKey: "optical_workshop",
    unitKeyForLaboratory: "optical_laboratory",
    area: "technical_services",
    kind: "technical_service",
    title: "Reparații rame și ochelari",
    publicLabel: "Reparații ochelari",
    description: "Reparații ale ramei și componentelor, în limitele dotării tehnice a atelierului.",
    items: [
      { group: "technical_activities", id: "eyeglasses_repair" },
      { group: "technical_activities", id: "frame_repair" },
    ],
  },
  {
    key: "workshop_lens_services",
    unitKey: "optical_workshop",
    unitKeyForLaboratory: "optical_laboratory",
    area: "technical_services",
    kind: "technical_service",
    title: "Montaj și înlocuire lentile",
    publicLabel: "Montaj și înlocuire lentile",
    description: "Montaj, înlocuire și comenzi tehnice pentru lentile și rame.",
    items: [
      { group: "technical_activities", id: "lens_fitting" },
      { group: "technical_activities", id: "lens_replacement" },
      { group: "technical_activities", id: "workshop_orders" },
    ],
  },
  {
    key: "general_ophthalmology",
    unitKey: "ophthalmology_office",
    area: "medical_services",
    kind: "medical_service",
    title: "Consultații și controale",
    publicLabel: "Consultații oftalmologice",
    description: "Consultații, controale și examinări efectuate de medicul oftalmolog.",
    note: "Serviciile medicale sunt publicate numai după verificarea medicului și a condițiilor necesare.",
    items: [
      { group: "ophthalmology_consults", id: "ophthalmology_consultation" },
      { group: "ophthalmology_consults", id: "complete_eye_exam" },
      { group: "ophthalmology_consults", id: "prescription_check" },
      { group: "ophthalmology_consults", id: "eye_pressure_check" },
      { group: "ophthalmology_consults", id: "fundus_exam" },
      { group: "ophthalmology_consults", id: "anterior_segment_exam" },
      { group: "ophthalmology_consults", id: "followup_consultation" },
      { group: "ophthalmology_consults", id: "second_opinion" },
    ],
  },
  {
    key: "investigations",
    unitKey: "ophthalmology_diagnostics",
    area: "medical_services",
    kind: "investigation",
    title: "Investigații și imagistică",
    publicLabel: "Investigații oftalmologice",
    description: "Investigații disponibile în funcție de aparatura verificată a locației.",
    items: [
      { group: "investigations", id: "oct" },
      { group: "investigations", id: "visual_field_analyzer" },
      { group: "investigations", id: "fundus_camera" },
      { group: "investigations", id: "pachymeter" },
      { group: "investigations", id: "biometer" },
      { group: "investigations", id: "corneal_topography" },
      { group: "investigations", id: "keratometry" },
      { group: "investigations", id: "tonometry" },
      { group: "investigations", id: "gonioscopy" },
      { group: "investigations", id: "ultrasound" },
      { group: "investigations", id: "specular_microscopy" },
      { group: "investigations", id: "angiography" },
    ],
  },
  {
    key: "retina_macula",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Retină și maculă",
    publicLabel: "Retină și maculă",
    description: "Evaluarea și monitorizarea afecțiunilor retiniene și maculare.",
    items: [
      { group: "specialties", id: "retina_consultation" },
      { group: "specialties", id: "diabetic_retinopathy" },
      { group: "specialties", id: "macular_degeneration" },
    ],
  },
  {
    key: "glaucoma",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Glaucom",
    publicLabel: "Glaucom",
    description: "Consultație și monitorizare specializată pentru glaucom.",
    items: [{ group: "specialties", id: "glaucoma_consultation" }],
  },
  {
    key: "cataract_refractive",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Cataractă și corecție refractivă",
    publicLabel: "Cataractă și chirurgie refractivă",
    description: "Evaluare specializată pentru cataractă și opțiuni de corecție refractivă.",
    items: [{ group: "specialties", id: "cataract_consultation" }],
  },
  {
    key: "cornea_surface",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Cornee și suprafață oculară",
    publicLabel: "Cornee și suprafață oculară",
    description: "Cornee, ochi uscat și servicii de management al miopiei.",
    items: [
      { group: "specialties", id: "cornea_consultation" },
      { group: "specialties", id: "dry_eye_management" },
      { group: "specialties", id: "myopia_management" },
    ],
  },
  {
    key: "pediatric_strabismus",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Oftalmologie pediatrică și strabism",
    publicLabel: "Oftalmologie pediatrică",
    description: "Consultații, screening și monitorizare pentru copii.",
    items: [
      { group: "specialties", id: "pediatric_ophthalmology" },
      { group: "specialties", id: "strabismus" },
      { group: "children_and_prevention", id: "children_eye_exam" },
      { group: "children_and_prevention", id: "pediatric_refraction" },
      { group: "children_and_prevention", id: "amblyopia_screening" },
      { group: "children_and_prevention", id: "strabismus_screening" },
      { group: "children_and_prevention", id: "school_screening" },
      { group: "children_and_prevention", id: "myopia_control_children" },
      { group: "children_and_prevention", id: "vision_therapy" },
    ],
  },
  {
    key: "neuro_inflammation",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Neuro-oftalmologie și inflamații",
    publicLabel: "Neuro-oftalmologie și uveită",
    description: "Evaluare specializată pentru afecțiuni neuro-oftalmologice și inflamatorii.",
    items: [
      { group: "specialties", id: "neuro_ophthalmology" },
      { group: "specialties", id: "uveitis" },
    ],
  },
  {
    key: "emergency_ophthalmology",
    unitKey: "ophthalmology_specialties",
    area: "medical_services",
    kind: "specialty",
    title: "Urgențe oftalmologice",
    publicLabel: "Urgențe oftalmologice",
    description: "Evaluarea urgențelor oftalmologice în limitele capacității locației.",
    items: [{ group: "specialties", id: "emergency_ophthalmology" }],
  },
  {
    key: "cataract_refractive_procedures",
    unitKey: "ophthalmology_procedures",
    area: "medical_services",
    kind: "procedure",
    title: "Cataractă și chirurgie refractivă",
    publicLabel: "Chirurgie cataractă și refractivă",
    description: "Intervenții care necesită medic, aparatură și infrastructură verificate.",
    items: [
      { group: "procedures_surgery", id: "cataract_surgery" },
      { group: "procedures_surgery", id: "refractive_surgery" },
      { group: "procedures_surgery", id: "yag_laser" },
    ],
  },
  {
    key: "retina_procedures",
    unitKey: "ophthalmology_procedures",
    area: "medical_services",
    kind: "procedure",
    title: "Proceduri retiniene și laser",
    publicLabel: "Proceduri retiniene și laser",
    description: "Laser retinian, injecții și alte proceduri specializate.",
    items: [
      { group: "procedures_surgery", id: "laser_procedures" },
      { group: "procedures_surgery", id: "retinal_laser" },
      { group: "procedures_surgery", id: "intravitreal_injections" },
    ],
  },
  {
    key: "oculoplastics_minor",
    unitKey: "ophthalmology_procedures",
    area: "medical_services",
    kind: "procedure",
    title: "Oculoplastică și proceduri minore",
    publicLabel: "Oculoplastică și proceduri minore",
    description: "Proceduri pentru pleoape și intervenții oftalmologice minore.",
    items: [
      { group: "procedures_surgery", id: "eyelid_surgery" },
      { group: "procedures_surgery", id: "chalazion_treatment" },
      { group: "procedures_surgery", id: "minor_eye_procedures" },
    ],
  },
];

export const PROVIDER_SERVICE_SECTION_BY_KEY = Object.fromEntries(
  PROVIDER_SERVICE_SECTIONS.map((section) => [section.key, section]),
);
