export const BASE44_FUNCTION_ROUTES: Record<string, string> = {
  "adminDataIntegrityOps": "directoryOps",
  "adminDirectoryCorrectionReview": "directoryOps",
  "adminOrganizationProfileReview": "directoryOps",
  "adminProfessionalProfileReview": "directoryOps",
  "adminProviderClaimReview": "directoryOps",
  "adminProviderScopedClaimReview": "directoryOps",
  "adminServiceConfigurationReview": "directoryOps",
  "adminServicePrerequisiteReview": "directoryOps",
  "adminWorkspaceReview": "directoryOps",
  "aiResearchOps": "directoryOps",
  "backfillLocationServiceMatching": "directoryOps",
  "backfillProviderOrganizationProfile": "directoryOps",
  "directoryImportOps": "directoryOps",
  "directoryMappingOps": "directoryOps",
  "geoImportOps": "directoryOps",
  "getAdminServiceManagementData": "directoryOps",
  "researchOps": "directoryOps",
  "reviewProfileChanges": "directoryOps",
  "getMyAccountDeletionEligibility": "getMyProviderWorkspace",
  "getMyProviderMembers": "getMyProviderWorkspace",
  "getMyProviderOnboardingWorkspace": "getMyProviderWorkspace",
  "getProviderEntitlement": "getMyProviderWorkspace",
  "getProviderLocationComparison": "getMyProviderWorkspace",
  "getProviderLogoReviewStatus": "getMyProviderWorkspace",
  "getProviderProfileCompleteness": "getMyProviderWorkspace",
  "getProviderWorkspaceOverview": "getMyProviderWorkspace",
  "acceptProviderMemberInvitation": "createProviderMemberInvitation",
  "deactivateProviderMember": "createProviderMemberInvitation",
  "reactivateProviderMember": "createProviderMemberInvitation",
  "revokeProviderMemberInvitation": "createProviderMemberInvitation",
  "listProviderMemberInvitations": "createProviderMemberInvitation",
  "setProviderMemberAccess": "createProviderMemberInvitation",
  "updateProviderMemberRole": "createProviderMemberInvitation",
  "syncProviderOrganizationOwnerAccess": "createProviderMemberInvitation",
  "submitProviderScopedClaim": "submitProviderClaim",
  "getProviderClaimScopeOptions": "submitProviderClaim",
  "providerLocationExpansionOps": "submitProviderClaim",
  "providerLocationIdentityResolutionOps": "submitProviderClaim",
  "providerLocationLifecycleOps": "submitProviderClaim",
  "updateProviderLocation": "submitProviderClaim",
  "getProviderServiceConfiguration": "providerServiceConfigurationOps",
  "getProviderLocationServices": "providerServiceConfigurationOps",
  "copyProviderServiceConfiguration": "providerServiceConfigurationOps",
  "copyProviderOpeningHours": "providerServiceConfigurationOps",
  "saveProviderOperatingHours": "providerServiceConfigurationOps",
  "saveProviderRoutineProfile": "providerServiceConfigurationOps",
  "submitProviderWorkspaceChange": "providerServiceConfigurationOps",
  "manageProviderOrganizationProfile": "providerServiceConfigurationOps",
  "profileFoundationOps": "providerServiceConfigurationOps",
  "locationPhotoOps": "providerServiceConfigurationOps",
  "providerPhotoUploadLifecycleOps": "providerServiceConfigurationOps",
  "preserveLegacyLocationLogo": "providerServiceConfigurationOps",
  "submitProviderLogoForReview": "providerServiceConfigurationOps",
  "manageMyProfessionalProfile": "getMyProfessionalWorkspace",
  "manageProfessionalAssignment": "getMyProfessionalWorkspace",
  "professionalInvitationOps": "getMyProfessionalWorkspace"
};

export function invokeConsolidatedFunction(base44: any, functionName: string, payload: unknown = {}) {
  const router = BASE44_FUNCTION_ROUTES[functionName];
  if (!router) return base44.functions.invoke(functionName, payload);
  return base44.functions.invoke(router, { __function: functionName, payload });
}
